### ISSUE TITLE
Make bordered container behind the image

### ISSUE THREAD

**Issue by amarjeetrao** [amarjeetrao/Tribute-Page-FreeCodeCamp#2]
Set the bordered container box behind the girl image. So that her image can easily seen.

**Fix suggestion : their might be z - index is set on the border container make it negative value.**

Feel free to ask anything, and please comment before working on it.

![Untitled](https://user-images.githubusercontent.com/33197010/66626715-e829cd00-ec16-11e9-8fb9-3d708e362c28.png)

**Comment by kalpananegi** [comment]
Should I?

**Comment by Johan-Ng** [comment]
Can I take part in this?

**Comment by amarjeetrao** [comment]
@Johan-Ng @kalpananegi, guys @melissagnzx already working on this. 
i'll post further issues if anything needed.

**Comment by Johan-Ng** [comment]
Ok, thanks!

**Comment by kalpananegi** [comment]
Ok, thanks!
